language: elm
elm-test: 0.19.0-rev6
node_js:
- '8'
script: yarn test
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: 6p8it6uJQBOYPKIldZ6FLC2uNUw75JPOV736tg8bZkPFSYpYp30loZBM6ZS2vusgq+/TFJxPgVjOIDm7OcI9Z2ZBIQNyUvZhk73OqiHbg8Yy301ffPhQyCURMwJAFuX4LAdkP5UYNOPKtuHQiUvfOhlmuMwyDNQQddBUppcHZZaE1ntj4w9liVECHhVJy/dB9tjL/lF4CZGnL5eyJydaWE9YM3o34MxliU/66Jv0YBeJjfk7C/GGkpIWK9uOMhlBJWxb421ChWOx/1GKnMqmDgkMwMSIcRh8Z+4H6JEw1vLY+SgKKrKlntk3mw8+KO9BSrw4M0k/cJX7V4Y2shU4ssxYlpzdxlK/zhj+Kyc9zU9VOgkVLzHfAluZxZvbJ7l34CcI8FQ7nT12/u/g4FaptCycEL8WnAS/Pksm5sBp+kQFLN9UHd9CRm8cfAys1i/1Z+U03Y4isg880CXZnKoMOV5iq79v4+9R8+u4KUPrPYN2KGTINbrLzpez7U1/6pFkXUt3BJGmM3pQhYYJ59PrHxo8GDPYSO/vAVpDLIDxOklJpFerG1PtZNa9TaCyvNlTH2h6xtkhcUN0RlBvrVu3eJ6CK4snoIDD/miIRCIEK3XpXVpp/hdHBavMHvTLfFYSi4I8bW7h8K49vG4hQRhrWAw3QzMJwSPi07/opB2yhaE=
